# Generated by Django 6.0 on 2025-12-10 11:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., JHS 1, Basic 7', max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Class (Grade)',
                'verbose_name_plural': 'Classes (Grades)',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Subjects',
                'ordering': ('name',),
            },
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ('-date_created',)},
        ),
        migrations.AlterModelOptions(
            name='questionpaper',
            options={'ordering': ('class_level', 'term', 'subject', 'title')},
        ),
        migrations.AddField(
            model_name='questionpaper',
            name='is_paid',
            field=models.BooleanField(default=True, help_text='Is this a paid paper or a free sample?'),
        ),
        migrations.AddField(
            model_name='questionpaper',
            name='slug',
            field=models.SlugField(default=uuid.uuid4, max_length=200),
        ),
        migrations.AddField(
            model_name='questionpaper',
            name='class_level',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='papers', to='shop.classes'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questionpaper',
            name='subject',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='papers', to='shop.subject'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., Term 1, Term 2', max_length=50)),
                ('slug', models.SlugField()),
                ('class_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terms', to='shop.classes')),
            ],
            options={
                'verbose_name_plural': 'Terms',
                'ordering': ('name',),
                'unique_together': {('class_name', 'slug')},
            },
        ),
        migrations.AddField(
            model_name='questionpaper',
            name='term',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='papers', to='shop.term'),
            preserve_default=False,
        ),
    ]
