# Generated by Django 6.0 on 2025-12-10 13:49

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_classes_subject_alter_payment_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionpaper',
            name='slug',
            field=models.SlugField(default=uuid.uuid4, max_length=200, unique=True),
        ),
    ]
