# Generated by Django 6.0 on 2025-12-12 19:14

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_questionpaper_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ('-date_created',), 'verbose_name': 'Payment', 'verbose_name_plural': 'Payments'},
        ),
        migrations.AlterModelOptions(
            name='questionpaper',
            options={'ordering': ('class_level', 'term', 'subject', 'title'), 'verbose_name': 'Question Paper', 'verbose_name_plural': 'Question Papers'},
        ),
        migrations.AddField(
            model_name='questionpaper',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questionpaper',
            name='description',
            field=models.TextField(blank=True, help_text='Description of the paper'),
        ),
        migrations.AddField(
            model_name='questionpaper',
            name='exam_type',
            field=models.CharField(choices=[('midterm', 'Mid-Term Exam'), ('endterm', 'End-Term Exam'), ('cat', 'CAT (Continuous Assessment Test)'), ('assignment', 'Assignment'), ('final', 'Final Exam'), ('mock', 'Mock Exam'), ('others', 'Others')], default='endterm', max_length=50),
        ),
        migrations.AddField(
            model_name='questionpaper',
            name='file_size',
            field=models.CharField(blank=True, editable=False, max_length=20),
        ),
        migrations.AddField(
            model_name='questionpaper',
            name='is_available',
            field=models.BooleanField(default=True, help_text='Is this paper available for purchase?'),
        ),
        migrations.AddField(
            model_name='questionpaper',
            name='pages',
            field=models.IntegerField(default=1, help_text='Number of pages'),
        ),
        migrations.AddField(
            model_name='questionpaper',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='questionpaper',
            name='views',
            field=models.IntegerField(default=0, help_text='Number of times viewed'),
        ),
        migrations.AddField(
            model_name='questionpaper',
            name='year',
            field=models.IntegerField(default=2025, help_text='Year the paper was administered'),
        ),
        migrations.CreateModel(
            name='DownloadHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.EmailField(max_length=254)),
                ('downloaded_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='downloads', to='shop.questionpaper')),
            ],
            options={
                'verbose_name': 'Download History',
                'verbose_name_plural': 'Download Histories',
                'ordering': ('-downloaded_at',),
            },
        ),
    ]
