# Generated by Django 6.0 on 2025-12-13 16:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_payment_options_alter_questionpaper_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FreeSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True)),
                ('sample_pdf', models.FileField(blank=True, null=True, upload_to='free_samples/')),
                ('downloads', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.AlterModelOptions(
            name='downloadhistory',
            options={'ordering': ('-downloaded_at',), 'verbose_name_plural': 'Download Histories'},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ('-date_created',)},
        ),
        migrations.AddField(
            model_name='downloadhistory',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='downloads', to='shop.payment'),
        ),
        migrations.AddField(
            model_name='downloadhistory',
            name='user_agent',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='amount_paid',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(default='paystack', max_length=50),
        ),
        migrations.AddField(
            model_name='payment',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='downloadhistory',
            name='user_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='question_paper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='shop.questionpaper'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='ref',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='questionpaper',
            name='password',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='questionpaper',
            name='pdf_file',
            field=models.FileField(help_text='Upload PDF question paper', max_length=500, upload_to='question_papers/'),
        ),
        migrations.AddIndex(
            model_name='questionpaper',
            index=models.Index(fields=['slug'], name='shop_questi_slug_fd2524_idx'),
        ),
        migrations.AddIndex(
            model_name='questionpaper',
            index=models.Index(fields=['class_level', 'term', 'subject'], name='shop_questi_class_l_bf4478_idx'),
        ),
        migrations.AddIndex(
            model_name='questionpaper',
            index=models.Index(fields=['is_available', 'is_paid'], name='shop_questi_is_avai_ff0744_idx'),
        ),
        migrations.AddField(
            model_name='freesample',
            name='question_paper',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='free_sample', to='shop.questionpaper'),
        ),
    ]
