"""
Django settings for MoMoDownloadSite project.
Generated by 'django-admin startproject' using Django X.X.
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx' # Use your actual secret key

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['127.0.0.1',          # Allows access from the loopback address
    'localhost',          # Allows access using 'localhost'
    'beamily-uncrannied-deane.ngrok-free.dev']

# ====================================================================
# 🔑 CUSTOM SETTINGS: API KEYS AND CURRENCY
# ====================================================================

# MoMoDownloadSite/MoMoDownloadSite/settings.py
# ...
# Get these from your Paystack Dashboard (TEST KEYS)
PAYSTACK_PUBLIC_KEY = 'pk_test_b961228a1baf0fd4171bce48a7df0fc5b8de0f4c' 
PAYSTACK_SECRET_KEY = 'sk_test_307b3abb76fde283fa1a6c809c3494c60797ee91'
# ...

# 2. SMS (Arkesel) Key (Replace placeholder with your actual key)
ARKESEL_API_KEY = 'your_arkesel_api_key_from_dashboard'

# 3. Currency Setting
CURRENCY_CODE = 'GHS' # Ghana Cedi

# ====================================================================
# APPLICATION DEFINITION
# ====================================================================

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # CRITICAL: Your custom application for the store logic
    'shop', 
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'MoMoDownloadSite.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'MoMoDownloadSite.wsgi.application'


# ====================================================================
# 💾 DATABASE FIX: This section MUST be correct for 'migrate' to work.
# ====================================================================

DATABASES = {
    'default': {
        # CRITICAL: Engine line must be present to tell Django to use SQLite.
        'ENGINE': 'django.db.backends.sqlite3', 
        # Points to the database file in the project root.
        'NAME': BASE_DIR / 'db.sqlite3', 
    }
}


# ====================================================================
# PASSWORD VALIDATION
# ====================================================================

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
STATIC_URL = 'static/'

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'